export const GLOBAL_ERROR = "GLOBAL_ERROR";

export const FETCH_START = "FETCH_START";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
export const FETCH_ADDITIVE_SUCCESS = "FETCH_ADDITIVE_SUCCESS";

export const SEARCH_FAST_START="SEARCH_FAST_START";
export const SEARCH_FAST_SUCCESS = "SEARCH_FAST_SUCCESS";
export const SEARCH_FAST_ERROR = "SEARCH_FAST_ERROR";


export const FETCH_FILTER_SUCCESS = "FETCH_FILTER_SUCCESS";
export const INITIAL_FETCH_SUCCESS = "INITIAL_FETCH_SUCCESS";


export const FETCH_MAIN_SLIDER_SUCCESS = "FETCH_MAIN_SLIDER_SUCCESS";
export const FETCH_REVIEWS_LIST_SUCCESS = "FETCH_REVIEWS_LIST_SUCCESS";